- name: Install docker
  hosts: _ansible_postgresql
  become: true
  tasks:
    # - name: upgrade all packages
    #   ansible.builtin.yum: 
    #     name: '*'
    #     state: latest
    # - name: Remove docker if installed from CentOS repo
    #   ansible.builtin.yum:
    #     name:
    #       - docker
    #       - docker-client
    #       - docker-client-latest
    #       - docker-common
    #       - docker-latest
    #       - docker-latest-logrotate
    #       - docker-logrotate
    #       - docker-engine
    #     state: removed
    
    # - name: Install yum utils
    #   ansible.builtin.yum:
    #     name: "yum-utils"
    #     state: latest

    # - name: Add Docker repo
    #   ansible.builtin.get_url:  #Downloads files from HTTP, HTTPS, or FTP
    #     url: https://download.docker.com/linux/centos/docker-ce.repo
    #     dest: /etc/yum.repos.d/docker-ce.repo    #Absolute path of where to download the file to.
    #  # https://docs.ansible.com/ansible/2.3/get_url_module.html

    # - name: Install Docker
    #   ansible.builtin.package:
    #     name: docker-ce
    #     state: latest

    # - name: Add user ec2-user to docker group
    #   ansible.builtin.user:
    #     name: ec2-user
    #     groups: docker
    #     append: yes   
    #     # usermod -a -G docker ec2-user

    # - name: Start Docker service
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: yes

    - name: copy files to the postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible-project/postgres/
        dest: /home/ec2-user/postgresql
  
    - name: remove cw_postgre container
      community.docker.docker_container:
        name: cw_postgre
        state: absent
        force_kill: true  

    - name: remove clarusway/postgre image
      community.docker.docker_image:
        name: clarusway/postgre
        state: absent

    - name: build container image
      community.docker.docker_image:
        name: clarusway/postgre
        build:
          path: /home/ec2-user/postgresql
        source: build
        state: present
      register: image_info
        # https://docs.ansible.com/ansible/2.9/modules/docker_image_module.html 
        # docker build -t olivercw/postgre . 

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: Launch postgresql docker container
      community.docker.docker_container:
        name: cw_postgre
        image: clarusway/postgre
        state: started
        ports: 
        - "5432:5432"
        env:
          # POSTGRES_PASSWORD: "{{ password }}"
          POSTGRES_PASSWORD: "Pp123456789" 
        volumes:
          - /db-data:/var/lib/postgresql/data   
      register: container_info
        # docker run --name oliver_postgre -e POSTGRES_PASSWORD=Pp123456789 -p 5432:5432 -d olivercw/postgre:latest 
    
    - name: print the container info
      ansible.builtin.debug:
        var: container_info